apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-go-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: consumer-go
  template:
    metadata:
      labels:
        app: consumer-go
    spec:
      containers:
        - name: consumer-go
          imagePullPolicy: Never
          image: webhook-demo/consumer-go:latest 
          ports:
            - containerPort: 8080 