apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  type: NodePort
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: 3001 # The port exposed by the service
      targetPort: 3001 # The port the producer app listens on
      nodePort: 30001