apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  replicas: 1 # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          imagePullPolicy: Never
          image: webhook-demo/producer:latest
          ports:
            - containerPort: 3001